@echo off
REM WSL wrapper for netMHCpan — auto-generated by setup_windows.ps1
REM Translates Windows file paths to WSL paths and runs the Linux binary via WSL
REM __WSL_DIR__ is replaced with the actual WSL path during setup

setlocal EnableDelayedExpansion
set "NMHOME=__WSL_DIR__"
set "NETMHCpan=%NMHOME%/Linux_x86_64"
set "ALLARGS="

:loop
if "%~1"=="" goto :run
if "%~1"=="-f" (
    shift
    call :winToWsl "%~f1" WSLPATH
    set "ALLARGS=!ALLARGS! -f !WSLPATH!"
) else if "%~1"=="-p" (
    shift
    call :winToWsl "%~f1" WSLPATH
    set "ALLARGS=!ALLARGS! -p !WSLPATH!"
) else (
    set "ALLARGS=!ALLARGS! %~1"
)
shift
goto :loop

:run
wsl bash -c "export TMPDIR=/tmp && !NETMHCpan!/bin/netMHCpan !ALLARGS!"
goto :eof

:winToWsl
setlocal
set "P=%~1"
set "P=!P:\=/!"
set "D=!P:~0,1!"
call :lower D
set "P=/mnt/!D!!P:~2!"
endlocal & set "%~2=%P%"
goto :eof

:lower
for %%i in (a b c d e f g h i j k l m n o p q r s t u v w x y z) do set "%~1=!%~1:%%i=%%i!"
goto :eof
